### ISSUE TITLE
Add import formats from other projects

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#21]
I noted that there are nearly 90 YNAB CSV projects. I want to contact each of them and ask for their CSV format. This ticket is my reminder to do that.

**Edit 1:** Here's a checklist in alphabetical order of all the repositories I've found ([source](https://github.com/https://github.com/search?utf8=%E2%9C%93&q=ynab+convert&type=Repositories) / [recent](https://github.com/search?o=desc&q=ynab+convert&s=updated&type=Repositories&utf8=%E2%9C%93)). Checked off when I have analysed them. 
**Edit 2:** @nocalla added some subheadings to try make this list a bit more comprehensible. Try to make headings for scripts for specific banks if there are duplicates, as this will be the most efficient way for us to incorporate individual banks. Create an issue for each identified bank and use the `bank format` label to track - link the issue number back to the relevant entry on this list.
**Edit 3:** @nocalla has changed the checkmarks to mean that they have been made into an issue

I am adding the formats to [our survey](https://goo.gl/forms/b7SNwTxmQFfnXlMf2). ([Results are here](https://docs.google.com/spreadsheets/d/1KmDkLWEx-aVMlUWpNXafovt6B9GbeDDZ2OruaOp_aqE/edit?usp=sharing).)

# **Issue Created**
[Link to relevant issue search](https://github.com/torbengb/bank2ynab/issues?q=is%3Aissue+is%3Aopen+label%3A%22bank+format%22+sort%3Acomments-desc)

- [x] #89 Handelsbanken [SE]
    - [joacand/HandelsbankenYNABConverter](https://github.com/joacand/HandelsbankenYNABConverter)
    - [jkauppinen/FinnishYnabCvsConverter](https://github.com/jkauppinen/FinnishYnabCvsConverter) (not entirely sure if this is the same bank)
- [x] #90 Rabobank [NL]
    - [Remco32/rabobank-to-ynab-converter](https://github.com/Remco32/rabobank-to-ynab-converter)
    - [BrianSetz/rabonab](https://github.com/BrianSetz/rabonab)
    - [canassa/rabobank-ynab](https://github.com/canassa/rabobank-ynab)
    - [eddokloosterman/php-rabobank-ynab-csv-converter](https://github.com/eddokloosterman/php-rabobank-ynab-csv-converter)
    - [jtdev/ynab-converter](https://github.com/jtdev/ynab-converter) [java]
    - [karsalfrink/RabobankToYNAB](https://github.com/karsalfrink/RabobankToYNAB) [Python] 
    - [tjukker/YNAB-bank-statement-converters](https://github.com/tjukker/YNAB-bank-statement-converters)
    - [rvgate/YnabConverter](https://github.com/rvgate/YnabConverter)
- [x] #91 ING [NL] 
    - [AndreSomers/ING2YNAB](https://github.com/AndreSomers/ING2YNAB)
    - [dive/ing-to-ynab-json-converter](https://github.com/dive/ing-to-ynab-json-converter) 
    - [ernezt/ynab-ing-converter](https://github.com/ernezt/ynab-ing-converter)
    - [Remco32/ing-to-ynab-converter](https://github.com/Remco32/ing-to-ynab-converter)
    - [mvd81/ynabconverter](https://github.com/mvd81/ynabconverter) [PHP]
- [x] #92 Nordea [NO]
    - [bivainis/ynab-csv-nordea](https://github.com/bivainis/ynab-csv-nordea)
    - [davols/nordea-ynab-convert](https://github.com/davols/nordea-ynab-convert)
    - [cosminlupu/to-ynab](https://github.com/cosminlupu/to-ynab)
    - [balvig/ynab_import](https://github.com/balvig/ynab_import)
- [x] #93 JLP [UK]
    - [JamesBelchamber/ynab-jlp-csv-converter](https://github.com/JamesBelchamber/ynab-jlp-csv-converter)
    - [clancychilds/jlp-ynab-converter](https://github.com/clancychilds/jlp-ynab-converter)
- [x] #94 Amex [International?] [akirayamamoto/amexcleaner](https://github.com/akirayamamoto/amexcleaner)
- [x] #95 Danksebank [DK]
    - [mywonderchild/YNAB-CSV-Converter](https://github.com/mywonderchild/YNAB-CSV-Converter) [Python]
    - [trahkoi/ynab-danske-csv](https://github.com/trahkoi/ynab-danske-csv)
    - [andsens/ynab-csv-converter](https://github.com/andsens/ynab-csv-converter)
- [x] #96 Hypovereinsbank [DE] [andsens/ynab-csv-converter](https://github.com/andsens/ynab-csv-converter)
- [x] #97 Nordnet [SE] [andsens/ynab-csv-converter](https://github.com/andsens/ynab-csv-converter)
- [x] #98 Sparekassen Kronjylland [DK] [andsens/ynab-csv-converter](https://github.com/andsens/ynab-csv-converter)
- [x] #99 Barclaycard [DE] [ma-ver-ick/ynab-converter](https://github.com/ma-ver-ick/ynab-converter) [Python]
- [x] #100 Sparkasse [DE] [ma-ver-ick/ynab-converter](https://github.com/ma-ver-ick/ynab-converter) [Python]
- [x] #102 Purdue Federal [US] [wesmcouch/Purdue-Federal-You-Need-A-Budget-Converter-YNAB-](https://github.com/wesmcouch/Purdue-Federal-You-Need-A-Budget-Converter-YNAB-)
- [x] #103 Budapest Bank [HU] [trekdemo/bank2ynab.rb](https://github.com/trekdemo/bank2ynab.rb) 
- [x] #104 First National Bank [ZA] [toranome/fnb2ynab](https://github.com/toranome/fnb2ynab)
- [x] #105 Itaú Unibanco [BR]
    - [willybarro/ynab-tools](https://github.com/willybarro/ynab-tools)
    - [Panthro/Itaucard2YNAB](https://github.com/Panthro/Itaucard2YNAB)
- [x] #106 Bancolombia [CO] [Asgaroth/ynab](https://github.com/Asgaroth/ynab)
- [x] #107 Alfa-Bank [RU] [BatON-RW/ynab-csv-converters](https://github.com/BatON-RW/ynab-csv-converters)
- [x] #108 Mint [Other Budgeting Software]  [tehmikey/YNABFileConverter](https://github.com/tehmikey/YNABFileConverter)
- [x] #109 Simple.com [US] [spuder/simple-ynab](https://github.com/spuder/simple-ynab)
- [x] #110 Skandiabanken [SE] [sklirg/SkandiabankenDoesYNAB](https://github.com/sklirg/SkandiabankenDoesYNAB)
- [x] #112 Easybank [AT] [jbogard/EasyBankToYnab](https://github.com/jbogard/EasyBankToYnab)
- [x] #113 Betterment [US] [jat255/Betterment_to_YNAB](https://github.com/jat255/Betterment_to_YNAB)
- [x] #114 Metro Bank [UK] [Thau/metro-ynab-convert](https://github.com/Thau/metro-ynab-convert)
- [x] #115 BB&T
    - [sirbarrence/bbt_csv_to_ynab](https://github.com/sirbarrence/bbt_csv_to_ynab)
    - [phildopus/bbt-ynab-convert](https://github.com/phildopus/bbt-ynab-convert)
- [x] #116 Knab [NL] [sido/knab-to-ynab](https://github.com/sido/knab-to-ynab)
- [x] #117 Barclays [UK][scottrobertson/barclays-to-ynab](https://github.com/scottrobertson/barclays-to-ynab)
- [x] #118 Deutsche Sparkasse [DE] 
    - [Salem5/ConvertBankstatementForYNAB](https://github.com/Salem5/ConvertBankstatementForYNAB)
    - [git-commit/ynab-conversion-scripts](https://github.com/git-commit/ynab-conversion-scripts)
    - [DarkSmile92/YNABConverterPy](https://github.com/DarkSmile92/YNABConverterPy)
    - [heysl/csv-camt2ynab](https://github.com/heysl/csv-camt2ynab) {not 100% sure this is the right bank for this one}
- [x] #119 Siam Commercial Bank [TH] [ROldford/pdf2ynab](https://github.com/ROldford/pdf2ynab)
- [x] #120 Ally Cashback [US] [philtr/csv2ofx](https://github.com/philtr/csv2ofx)
- [x] #121 KB Bank [CZ] [rockwood/kb](https://github.com/rockwood/kb)
- [x] #122 Schwab [US] & #123 TD Bank [US][RichardLitt/ynab-convert-csv](https://github.com/RichardLitt/ynab-convert-csv)
- [x] #124 AXA Homebanking [BE] [PVandenheede/AXA2YNAB](https://github.com/PVandenheede/AXA2YNAB)
- [x] #125 Migros Bank [CH] [p-26/MigrosBankSwiftMessageParser](https://github.com/p-26/MigrosBankSwiftMessageParser)
- [x] #126 OCBC Bank [SG][fongming/OCBC-YNAB-Parser](https://github.com/fongming/OCBC-YNAB-Parser) [Python]
- [x] #127 Royal Bank of Scotland [UK] [jcalero/ynab-rbs-converter](https://github.com/jcalero/ynab-rbs-converter) [PHP]
- [x] #128 UBS [CH] [fahyik/UBS_YNAB](https://github.com/fahyik/UBS_YNAB)
- [x] #129 DNB [NO]
    - [cronin101/DNB-2-YNAB-CSVConverter](https://github.com/cronin101/DNB-2-YNAB-CSVConverter)
    - [Snikanes/ynab-convert](https://github.com/Snikanes/ynab-convert) 
- [x] #130 Alelo [BR] [figueredo/bank2ynab](https://github.com/figueredo/bank2ynab)
- [x] #131 Deutschebank [DE] [marfei/db-to-ynab](https://github.com/marfei/db-to-ynab) [C#]
- [x] #132 Deutsche Kreditbank [DE] [martinth/dkb-to-ynab](https://github.com/martinth/dkb-to-ynab) [Ruby]
- [x] #133 Finnish Osuuspankki [FI] [mixu-/ynab-csv](https://github.com/mixu-/ynab-csv) [Python]
- [x] #134 Swedbank [SE] [jpsk/Swedbank-to-YNAB4-converter](https://github.com/jpsk/Swedbank-to-YNAB4-converter)
- [x] #135 Banco Bradesco [BR] [pedroaxl/ynab-scripts](https://github.com/pedroaxl/ynab-scripts)
- [x] #136 OTP [HU] [abesto/otp2ynab](https://github.com/abesto/otp2ynab)
- [x] #137 N26 [DE] [DarkSmile92/YNABConverterPy](https://github.com/DarkSmile92/YNABConverterPy)
- [x] #138 Chase [US] [rennes-us/ynab-convert](https://github.com/rennes-us/ynab-convert)
- [x] #139 Shopify [E-Commerce Platform] [rennes-us/ynab-convert](https://github.com/rennes-us/ynab-convert)
- [x] #140 Cathay [?] [johnlinvc/ynab_tw](https://github.com/johnlinvc/ynab_tw)
- [x] #141 Consorsbank [DE] [nicolaipischel/YnabBankDataConverter](https://github.com/nicolaipischel/YnabBankDataConverter) [C#]
- [x] #142 Starmoney [Banking Software] [fpoppinga/ynab-converter](https://github.com/fpoppinga/ynab-converter)
- [x] #143 Selected Polish Banks (not sure which!) [PL] [mnowak/ynab-pl-converter](https://github.com/mnowak/ynab-pl-converter) [Java] this reads PDF files...
- [x] #144 Personal Capital [Banking Software] [mgrecar/pc_to_ynab](https://github.com/mgrecar/pc_to_ynab) [Ruby]
- [x] #145 KSK [DE] [Bockwurst2/ynab_csv](https://github.com/Bockwurst2/ynab_csv) This is all in German! I can't work it out
- [x] #146 Comdirect [DE] [Bockwurst2/ynab_csv](https://github.com/Bockwurst2/ynab_csv)

# **To Be Sorted**
- [ ] [this long list of country plugins for ofxstatement](https://github.com/kedder/ofxstatement#known-plugins)
- [ ] [dkusidlo/ynab_csv_converter](https://github.com/dkusidlo/ynab_csv_converter) I think this works for 4 different banks.  n26, taspa, diba, kospa are the names listed

# **Irrelevant/Empty/No bank specified**
- ~~[PhantomOverride/ynab4-csv](https://github.com/PhantomOverride/ynab4-csv)~~ No bank specified
- ~~[ashraymehta/statement-converter](https://github.com/ashraymehta/statement-converter)~~ No bank specified
- ~~[adnilsson/Bank2YNAB](https://github.com/adnilsson/Bank2YNAB)~~ Bank not specified
- ~~[KrisMysen/terra-to-ynab](https://github.com/KrisMysen/terra-to-ynab)~~ [java] this is an empty stub
- ~~[pgr0ss/ynab_to_ledger](https://github.com/pgr0ss/ynab_to_ledger)~~ this actually exports from Ynab to a program called Ledger.
- ~~[gallamine/CSV-to-YNAB](https://github.com/gallamine/CSV-to-YNAB)~~ empty
- ~~[mhusbyn/ynab-currency-converter](https://github.com/mhusbyn/ynab-currency-converter)~~ this converts ynab4 files to different currency, unrelated
- ~~[markov-a/YNAB-to-SQLite3](https://github.com/markov-a/YNAB-to-SQLite3)~~ This converts Ynab4 files to a SQLite database, unrelated.
- ~~[eqdw/ynabify](https://github.com/eqdw/ynabify)~~ General use library, no specific bank mentioned
- ~~[p-26/Mt940ToYnabConverter](https://github.com/p-26/Mt940ToYnabConverter)~~ Empty
- ~~[esnunes/bsbr-to-ynab](https://github.com/esnunes/bsbr-to-ynab)~~ Empty
- ~~[asteroidb612/nynab-ynab4](https://github.com/asteroidb612/nynab-ynab4)~~ Converter from nYNAB export to YNAB4 format
- ~~[rschoultz/SHB2YNAB](https://github.com/rschoultz/SHB2YNAB)~~ Empty
- ~~[mika-s/FinancialExchangeConverter](https://github.com/mika-s/FinancialExchangeConverter)~~ This is a general use one for converting csv files to a certain output format. 

# **Already Supported**
- AIB [IE] ~~[jasonmadigan/aib-to-ynab](https://github.com/jasonmadigan/aib-to-ynab)[JavaScript]~~ 
- AIB [IE] ~~[heedfull/AIBtoYNABCsvConverter](https://github.com/heedfull/AIBtoYNABCsvConverter)~~[Python]

**Comment by nocalla** [comment]
We need to make a standardised input format that they can fill in.

**Comment by torbengb** [comment]
Yes, I too was thinking about a survey form or shared spreadsheet. I like that we seem to think alike :+1:

**Comment by torbengb** [comment]
I can't help myself. I made this survey: https://goo.gl/forms/b7SNwTxmQFfnXlMf2 

It stores [responses in this spreadsheet](https://docs.google.com/spreadsheets/d/1KmDkLWEx-aVMlUWpNXafovt6B9GbeDDZ2OruaOp_aqE/edit?usp=sharing).

**Comment by nocalla** [comment]
I disagree with a line in your survey. "We only really care about the location of the columns Date + Payee + Amount. 
You can simply specify "skip" for any column that isn't relevant. " 

We care about all the YNAB columns, i.e. Date, Payee, Category, Memo, Outflow, Inflow.
Category obviously won't be there, but Outflow and Inflow should be treated separately. I know your bank just lists positive or negative amount, but that's handled by the code.

**Comment by nocalla** [comment]
Referencing Issue #17

**Comment by torbengb** [comment]
You are right! Thank you for this feedback, I will change the text to reflect what you said.

**Comment by torbengb** [comment]
I modified the survey text as per your suggestion. :+1:

**Comment by toyg** [comment]
There is a question of how much we can actually stretch the current approach of just reordering a few fields. For example, I'm looking at https://github.com/JamesBelchamber/ynab-jlp-csv-converter/blob/master/convert.py and apparently that bank (JLP) does not have different columns for Inflows and Outflows, but rather a single column for values that are marked as CR in another field when it's a credit. This is literally the first random script I picked from the list, chances are that there are loads of these. Special-casing this sort of thing will only get us so far.

What about adding the possibility of loading a different class that will do the record parsing and will then provide an iterator returning the necessary format? That way we can deal with untractable special cases in dedicated modules.

I'm thinking we could have a `modules` subfolder that contains, for example, a `jlp.py` file with some sort of class that provides a standard interface. Then in the config file the user could specify an option like `Parsing Module = jlp`. If the option is specified, the code will load the module and hand over parsing to it, expecting to get back an iterator that we can use with `csv`; otherwise, we do the regular parsing (in fact, we could have a `default.py` module that holds default parsing logic, shortening the main script). This is pretty easy in Python 3 with a bit of `importlib` magic, and I'm pretty sure there is a Python2 equivalent too.

As well as dealing with difficult special cases, this could potentially open the door to supporting pretty much any file format, not just csv.

**Comment by torbengb** [comment]
That's a good odd case you found, and a good approach even for other formats. 

Another thought would be to pick the low-hanging fruit (the formats that can be directly used with our current approach) and then deal with these harder cases if/when there is actual interest. I very much like the simplicity of the current one-file solution (okay, plus the config).

**Comment by nocalla** [comment]
It's a good idea to load specific modules that way.  I agree with @torbengb though, in that we should deal with the low hanging fruit first. The modules approach makes adding a format a bit more complex for the end user if they're modifying an actual py file also, but I do like the idea of it and think it's the way to go in the future.

**Comment by torbengb** [comment]
@toyg Would you like to open a new issue for that suggestion? We could label it `Enhancement` and `Milestone 2.0` so we don't lose track of it.

**Comment by toyg** [comment]
Opened #53

**Comment by nocalla** [comment]
I think we are in a position to start working through this list properly now. We need a better workflow for inputting format details though. Is using the survey cumbersome from a dev point of view? Should we just edit the Wiki page?

**Comment by torbengb** [comment]
I killed the wiki page because *that* was a pain in the ass to write. Wiki table cell markdown syntax isn't well suited for wide tables. We could just add directly into the [Google Sheets document](https://docs.google.com/spreadsheets/d/1KmDkLWEx-aVMlUWpNXafovt6B9GbeDDZ2OruaOp_aqE/edit?usp=sharing) and probably be happier that way.

**Comment by toyg** [comment]
I've written to the owner of the JLP converter mentioned above, I have a plugin ready but before I commit it I'd like a test file to keep as reference.

**Comment by adnilsson** [comment]
I wish to clarify that [my script ](https://github.com/adnilsson/Bank2YNAB) is for Nordea in Sweden, and should therefore be classified as Nordea [SE].  The [SE] version differs from [NO], e.g. they use different delimiters. See more details in my answer to the survey (row 14).

**Comment by nocalla** [comment]
Marking this as closed because we have the relevant issues created as standalones.
